### ISSUE TITLE
Not fully working in Ubuntu 18.04

### ISSUE THREAD

**Issue by cunidev** [rockon999/no-spring#1]
In Ubuntu 18.04, the spring animation is still shown when clicking the drawer button from desktop instead of clicking it from overview. Is the extension still being developed btw? Works fine for me on GNOME 3.28, though it's not declared in its manifest file...
Thanks

**Comment by ewlsh** [comment]
Hi! Yes it is still under development, I just haven't had the time to update the version spec. Ubuntu 18.04 uses Dash to Dock (or a fork of it). Dash to Dock has a setting that enables/disables the spring animation from the dock. If you enable this setting it will override this extension.

**Comment by cunidev** [comment]
I see, thank you! I suggest adding the version spec, as it should work perfectly in 3.28.
